version: '3.8'

services:
  granite-agent:
    build: .
    ports:
      - "12000:12000"
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - PORT=12000
    restart: unless-stopped
    # Uncomment the following lines if you have NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12000/", "&&", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 120s  # Extended for model download time

volumes:
  ollama_data:
    driver: local
